### PR TITLE
Featurews

### PR DESCRIPTION
**Pull request by MasomRezaie**
This pull request introduces HTML and CSS files for a form submission. The form is designed to gather user input and submit it to the server.

Changes:
Added index.html file containing the HTML structure for the form.
Added styles.css file for styling the form elements.
Linked styles.css to index.html for applying the styles.

Details:
The index.html file contains:

In the first has a container and the Form element with fields for user input (e.g., name, email, phone number, select option, description, checkbox, radio button ).
Submit button to send the form data.
Basic structure and necessary attributes for accessibility and usability.

The styles.css file includes:
Styling for form elements, including container class input fields, labels, and the submit button.
Clear and readable typography for better user experience.

### CODE REVIEW

**Comment by ahzamir** [comment]
@MasomRezaie 

- I can not provide you feedback till you don't solve your project linters issues.
- Solve the linters issues and mention me using my username @ahzamir here in a comment so I can review your project.

**Comment by ahzamir** [comment]
### Hi @MasomRezaie 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

- [GitHub Flow] You also pushed some of your codes into the Development branch which is also a bad practice. To solve this You can create a new repo implement all your changes and use the GitHub flow properly!

- You have done a great job by adding this design to your code 🎉✔️👍
Screenshot 2024-05-18 170346

# Status: Required Changes 🔁 ❌
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
❌ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by MasomRezaie** [comment]
@ahzamir, sir my project passed the freecodecamp test.

**Review by ahzamir — APPROVED** [review]
### Hi @MasomRezaie 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
Screenshot 2024-05-18 170346


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Tribute Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
